# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BusBookingSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ACPAnalytics', '~> 2.0'
  pod 'ACPUserProfile', '~> 2.0'
  pod 'ACPCore', '~> 2.0'
  pod 'ACPGriffonBeta'

  # Pods for BusBookingSwift

end
